### ISSUE TITLE
Feature: Desktop notifications

### ISSUE THREAD

**Issue by boedy** [jeffaco/duplicacy-util#10]
The possibility to get email notifications is nice, but a bit overkill for my need. I wouldn't want my inbox to get littered with daily backup reports. I suspect that a desktop notification will give me enough feedback to go on. Some design considerations:
- [x] Alert on error
- [ ] Notify on success?
- [x] Enabled by default?

The https://github.com/gen2brain/beeep package could be implemented to get desktop notifications working. @jeffaco If you like I could draft a PR. Would first like to have some consensus on its requirements though.

**Comment by jeffaco** [comment]
@boedy What are your thoughts on my feedback?

**Comment by boedy** [comment]
Sorry for not getting back to you sooner. Had some work to catch up on. Thanks for info on the email notification part. I jumped to conclusions there. I should play with it a bit more to see if it fits me flow.

I think putting a notification config it in the global initialisation file works. But you should be able choose through which `channels` you get notified. I like the push notifications idea. This would be my preferred approach for headless systems or computers I don't access often. In the future you could possible add extra notification `channels`. Pushbullet, Slack or Webhook support would be on the top of my list.

I realised it would be good to have an `onStart` notification. I regularly work on the go where I use my phones cellular connection. I wouldn't want `duplicacy` burning🔥  through my monthly bandwidth then. Would be nice to skip the backup by clicking on the notification. Another way of solving this would be whitelisting / blacklisting WiFi SSID's, but thats out of scope for this feature. This is what I ended up with for now:
```
notifications:
    channel: desktop, email (default: email, desktop)
    events:
        onSuccess: true or false (default: false)
        onFailure: true or false (default: true)
        onStart: true or false (default: false)
```
How's that? Would the cli option flags `-em` and `-tm` change as well? 

[Beeep](https://github.com/gen2brain/beeep) uses simple system wrappers. I did some testing on my macbook and noticed custom icons are not supported with the current implementation (see https://github.com/gen2brain/beeep/issues/15). I haven't tested the the other platforms. [Beeep](https://github.com/gen2brain/beeep) also does not support custom click handlers. [gosx-notifier](https://github.com/deckarep/gosx-notifier) is an alternative package that features both images and click handlers which I think will allow you to pull up the log. It unfortunately supports macOS only though.

**Comment by jeffaco** [comment]
Hi @boedy Thanks for your response.

I think channels provide a fine way extend notifications in the future, and I like the concept, even if the first channels are just `desktop` and `email`. However, I assume if a channel isn't mentioned it would simply never be enabled? I wonder if people might want different notifications specified on a per-channel basis. For example, perhaps I want `onSuccess` for `email` but not for `desktop`. Thus, perhaps a better method might be:

```
notifications:
    1:
        channel: desktop
        events:
            ...
    2:
        channel: email
        events:
            ...
```

This allows you to specify an event mask on a per-channel basis, which might be preferred. And I guess, if you don't specify a channel at all, then it would never be notified.

There is no `-em` qualifier, you probably mean `-m` (to send mail). I think that `-m` has no purpose with the notification section that you defined above. However, it's defined today, so I'd probably keep it for backwards compatibility (at least until a `v2.0` release of `duplicacy-util`). Thus, if you didn't specify `-m`, then I'd look to the channels to see if email was enabled, and how to handle it. If `-m` was specified on the command line, that would server to override the `email` channel such that it was enabled for both success and failure (which is what it does now). I think that makes the most sense.

The `-tm` (test mail) would probably persist for backwards compatibility (again, until a `v2.0` release, if that ever happens). I'd probably add a new `-te` (test events) qualifier that would test each of the events that you set up for both success and failure (much like `-tm` does today, but just for e-mail).

I'm totally uninterested in implementing something that only works on a single platform. Part of the entire focus of `duplicacy-util` is that it runs everywhere with no fuss. But that said, if we supported [Beeep](https://github.com/gen2brain/beeep) for most platforms, but supported [gosx-notifier](https://github.com/deckarep/gosx-notifier) for richer capabilities on Mac OS/X, that's totally fine with me (and only partly because I use a Mac). Honestly, if certain platforms give richer capabilities, that's fine, as long as the basic capability still works properly on other platforms.

Thoughts?

**Comment by boedy** [comment]
@jeffaco Looks good. I do find the config you propose a bit verbose though. What about this:
```
notifications:
  onSuccess: ["desktop"]
  onFailure: ["desktop","email", "pushbullet", "slack"]
  onStart: ["desktop"]

email:
  fromAddress: "Donald Duck <donald.xyzzy@gmail.com>"
  toAddress: "Donald Duck <donald.xyzzy@gmail.com>"
  serverHostname: smtp.gmail.com
  serverPort: 465
  authUsername: donald.xyzzy@gmail.com
  authPassword: gaozqlwbztypagwt

slack:
  token: "342u34tu0xunqru2x5y23234234fdsfah4f"

pushBullet:
  token: "342u34tu0xunqru2x5y23234234fdsfah4f"
```
We would stick to the old configuration style for email to stay backward compatible for now. If channels is not configure correctly but defined in the notification section an error should be raised.

**Comment by jeffaco** [comment]
I was thinking of making those email changes anyway.

As for the formatting: I like your formatting, but I had difficulty with this sort of thing with [Viper](https://github.com/spf13/viper). If you can make Viper digest that in a reasonable way, I'm fine with your formatting.

If not, then I'd probably add event-specific data as part of the notification, like this:

```
notifications:
    2:
        channel: email
        events:
            onSuccess: true or false (default: false)
            onFailure: true or false (default: true)
            onStart: true or false (default: false)
        fromAddress: "Donald Duck <donald.xyzzy@gmail.com>"
        toAddress: "Donald Duck <donald.xyzzy@gmail.com>"
        serverHostname: smtp.gmail.com
        serverPort: 465
        authUsername: donald.xyzzy@gmail.com
        authPassword: gaozqlwbztypagwt
```

Then, once we read in the channel type, we'd know what to read in from there.

Since you were willing to do a pull request, may I suggest you add a `notify.go` implementation that reads in the new notification section (to be called from the `globalConfiguration.go` file). Once `globalConfiguration.go` sees a notifications section, it can dispatch off to `notify.go`. And these days, when writing new code, I always write unit tests for new code. So I'd humbly suggest that, if you could manage it. See existing code for examples.

I think a good start would be to get this working for E-Mail, then add other event types (like desktop first, and then others as we see fit). But E-Mail comes first, and sets the framework for things to follow.

Thoughts?
