### ISSUE TITLE
Storage definitions configuration file structure

### ISSUE THREAD

**Issue by plasticrake** [jeffaco/duplicacy-util#19]
Hi @jeffaco, thanks again for this great tool!

I'm writing some scripts to help automate duplicacy and duplicacy-util configuration and deployment (I hope to have ready to share soon), and I have some feedback on the storage definitions config file.

When I first read about this tool I had assumed the numbered keys for each item had meaning; `1:` under storage must refer to `1:` under prune, etc. But it appears this is not the case and they are really just an array defined with numbered keys. Also if you happen to skip any numbers in your file (perhaps from copying and pasting) example: 1,2,3,5,6 will only process 1,2,3 and skip 5 and 6.

Since these numbers don't have any meaning I propose they be removed. This will also simplify my tool that can generate these files.

Please let me know what you think, I can take a stab at implementing this in a backwards compatible way and submit a pull request if you're open to it.

Rewriting your example to the proposed format:

```yaml
repository: /Volumes/Quicken

storage:
  - name: b2
    threads: 10
  
  - name: azure-direct
    threads: 5

copy:
  - from: b2
    to: azure
    threads: 10

prune:
  - storage: b2
    keep: "0:365 30:180 7:30 1:7"

  - storage: azure
    keep: "0:365 30:180 7:30 1:7"

check:
  - storage: b2
    all: true
  
  - storage: azure
    all: true
```

**Comment by jeffaco** [comment]
Hi @plasticrake  Skipping numbers is a no-no, and is mentioned in the [README.md](https://github.com/jeffaco/duplicacy-util/blob/master/README.md) file.

These do have a meaning, as such: They form an order for backup/copy/prune/check operations. But to tell the truth, I had problems with the formatting that you proposed with [Viper](https://github.com/spf13/viper). The easiest fastest way around this was to format the YAML file as I had formatted it (makes the code to load this very simple). and doing so allowed me to quickly move on.

Personally, I don't think it's a big deal, as `1:` vs `-` doesn't matter a whole lot. But if you took the time to write things to presumably make it easier, I'd certainly be game for mentioning it in the [README.md](https://github.com/jeffaco/duplicacy-util/blob/master/README.md) file.

Given that I did originally try and format the way you proposed, I can take another look at this at some point (I certainly understand `Go` a lot better at this point). Or better yet, I'm happy to take a PR for this if you feel compelled to take care of this.

I would definitely want backwards compatibility, at least in the short term. But latest version (`1.4`) now has upgrade policies, so I would definitely structure the code to accept the old format but give a warning until some later release.

Anyway, if you feel compelled, feel free to take a look. Otherwise, I'll leave this open and look at it eventually. It's low on the priority list, though (things like push notifications are more important to me).

**Comment by jeffaco** [comment]
Looking at this a little closer, I see why I was confused before.

It's easy enough to look up static values (i.e. `storage.1.name`, `storage.1.threads`, etc). But it's not clear to me how to grab a variable list of items (which your format had):

```
storage:
  - name: b2
    threads: 10

  - name: azure-direct
    threads: 5
```

The `-` is indicating a variable length list, and it's not clear to me how to pick that up under Viper. If you want to come up with an example of how to read this, or better yet, just do a PR that will handle it, I'll happily take it.

Are other people having issues getting the configuration file set up properly? This seems simple enough to me but then I wrote it, so of course I'm going to understand it. I have a section in [README.md](https://github.com/jeffaco/duplicacy-util/blob/master/README.md#local-configuration-file) that covers this:

>The storage list contains a list of repositories to back up. Note that the list may be as
>long as required. duplicacy-util will continue loading monotonically increasing section
>numbers until no additional sections are found (i.e. 1, 2, 3).

I guess my question to the community is: Is this clear? Do I need a better explanation? Or is it super important to change the repository configuration file to get rid of section numbers?
