### ISSUE TITLE
Error: no storage locations defined in configuration

### ISSUE THREAD

**Issue by bodypilot** [jeffaco/duplicacy-util#27]
Hi,

This might be related to https://github.com/jeffaco/duplicacy-util/issues/19 although I'm not a developer so I'm not sure.

On Windows 10 I run into the following problem when running duplicacy-util:

> C:\Users\user>duplicacy-util -f Laptop-MC -a

```
20:38:53 Using global config: C:\Users\user\.duplicacy-util\duplicacy-util.yaml
Error: no storage locations defined in configuration
Error: no prune locations defined in configuration
Error: no check locations defined in configuration
```
Here's some extra info:

> duplicacy-util -version

`Version: 1.4, Git Hash: cad0ac7`

> C:\Users\user\\.duplicacy-util\Laptop-MC.yaml

```
repository: C:\Users\user

storage:
    -   name: rp3-32

prune:
    -   storage: rp3-32
        keep: "0:365 30:180 7:30 1:7"

check:
    -   storage: rp3-32
```
> C:\Users\user\\.duplicacy\preferences

```
[
    {
        "name": "rp3-32",
        "id": "Laptop-MC",
        "repository": "",
        "storage": "sftp://user@host//mnt/data/backup/Laptop-MC",
        "encrypted": true,
        "no_backup": false,
        "no_restore": false,
        "no_save_password": false,
        "nobackup_file": "",
        "keys": null
    }
]
```

A similar setup on my Linux laptop using the old scheme with numbers works well.

```
repository: /home/user

storage:
           1:
                          name: rp3-32

prune:
           1:
                         storage: rp3-32
                         keep: "0:365 30:180 7:30 1:7"

check:
            1:
                       storage: rp3-32
```
But  if I set this up under Windows 10 it doesn't work.
Am I doing something wrong or have I stumbled upon a bug?
