### ISSUE TITLE
Noob alert. Is there a duplicacy-util.yaml sample

### ISSUE THREAD

**Issue by anibalinbalin** [jeffaco/duplicacy-util#35]
That I can take a look at?
It would be much simpler if I could see a model of the file.
Thanks in advance.

**Comment by jeffaco** [comment]
A lot of this stuff is defaulted so you don't need much. My global configuration just has E-Mail configuration because the storage directory (`$HOME/.duplicacy-util`) exists since I created it.

Create, in your home directory, directory `.duplicacy-util`. Then, within it, create file `duplicacy-util.yaml`. It should contain E-Mail configuration like this:

```
email:
  fromAddress: "Donald Duck <donald.xyzzy@gmail.com>"
  toAddress: "Donald Duck <donald.xyzzy@gmail.com>"
  serverHostname: smtp.gmail.com
  serverPort: 465
  authUsername: donald.xyzzy@gmail.com
  authPassword: gaozqlwbztypagwt
```

That's it for your global configuration file, assuming you don't want to change defaults.

For the repository backup file, see this [README example](https://github.com/jeffaco/duplicacy-util#local-configuration-file). It's repository specific and backup service specific, but very easy to set up.

The README.md file has a wealth of information. Read it carefully. If you don't understand it, ask questions about that, and I'll happily explain (and modify or simplify the README.md if appropriate). But you have to be able to read and comprehend the README.md file to make use of this software. But please, if you don't understand it, ask questions - that way, you'll understand the file, and I'll make it more readable if appropriate.
